package com.example.community.model;

public class Notification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.NOTIFICATION.ID
     *
     * @mbg.generated Fri Jun 16 09:57:35 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.NOTIFICATION.NOTIFIER
     *
     * @mbg.generated Fri Jun 16 09:57:35 CST 2023
     */
    private Integer notifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.NOTIFICATION.RECEIVER
     *
     * @mbg.generated Fri Jun 16 09:57:35 CST 2023
     */
    private Integer receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.NOTIFICATION.OUTERID
     *
     * @mbg.generated Fri Jun 16 09:57:35 CST 2023
     */
    private Integer outerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.NOTIFICATION.TYPE
     *
     * @mbg.generated Fri Jun 16 09:57:35 CST 2023
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.NOTIFICATION.GMT_CREATE
     *
     * @mbg.generated Fri Jun 16 09:57:35 CST 2023
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.NOTIFICATION.STATUS
     *
     * @mbg.generated Fri Jun 16 09:57:35 CST 2023
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.NOTIFICATION.NOTIFIER_NAME
     *
     * @mbg.generated Fri Jun 16 09:57:35 CST 2023
     */
    private String notifierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.NOTIFICATION.OUTER_TITLE
     *
     * @mbg.generated Fri Jun 16 09:57:35 CST 2023
     */
    private String outerTitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.NOTIFICATION.ID
     *
     * @return the value of PUBLIC.NOTIFICATION.ID
     *
     * @mbg.generated Fri Jun 16 09:57:35 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.NOTIFICATION.ID
     *
     * @param id the value for PUBLIC.NOTIFICATION.ID
     *
     * @mbg.generated Fri Jun 16 09:57:35 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.NOTIFICATION.NOTIFIER
     *
     * @return the value of PUBLIC.NOTIFICATION.NOTIFIER
     *
     * @mbg.generated Fri Jun 16 09:57:35 CST 2023
     */
    public Integer getNotifier() {
        return notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.NOTIFICATION.NOTIFIER
     *
     * @param notifier the value for PUBLIC.NOTIFICATION.NOTIFIER
     *
     * @mbg.generated Fri Jun 16 09:57:35 CST 2023
     */
    public void setNotifier(Integer notifier) {
        this.notifier = notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.NOTIFICATION.RECEIVER
     *
     * @return the value of PUBLIC.NOTIFICATION.RECEIVER
     *
     * @mbg.generated Fri Jun 16 09:57:35 CST 2023
     */
    public Integer getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.NOTIFICATION.RECEIVER
     *
     * @param receiver the value for PUBLIC.NOTIFICATION.RECEIVER
     *
     * @mbg.generated Fri Jun 16 09:57:35 CST 2023
     */
    public void setReceiver(Integer receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.NOTIFICATION.OUTERID
     *
     * @return the value of PUBLIC.NOTIFICATION.OUTERID
     *
     * @mbg.generated Fri Jun 16 09:57:35 CST 2023
     */
    public Integer getOuterid() {
        return outerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.NOTIFICATION.OUTERID
     *
     * @param outerid the value for PUBLIC.NOTIFICATION.OUTERID
     *
     * @mbg.generated Fri Jun 16 09:57:35 CST 2023
     */
    public void setOuterid(Integer outerid) {
        this.outerid = outerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.NOTIFICATION.TYPE
     *
     * @return the value of PUBLIC.NOTIFICATION.TYPE
     *
     * @mbg.generated Fri Jun 16 09:57:35 CST 2023
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.NOTIFICATION.TYPE
     *
     * @param type the value for PUBLIC.NOTIFICATION.TYPE
     *
     * @mbg.generated Fri Jun 16 09:57:35 CST 2023
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.NOTIFICATION.GMT_CREATE
     *
     * @return the value of PUBLIC.NOTIFICATION.GMT_CREATE
     *
     * @mbg.generated Fri Jun 16 09:57:35 CST 2023
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.NOTIFICATION.GMT_CREATE
     *
     * @param gmtCreate the value for PUBLIC.NOTIFICATION.GMT_CREATE
     *
     * @mbg.generated Fri Jun 16 09:57:35 CST 2023
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.NOTIFICATION.STATUS
     *
     * @return the value of PUBLIC.NOTIFICATION.STATUS
     *
     * @mbg.generated Fri Jun 16 09:57:35 CST 2023
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.NOTIFICATION.STATUS
     *
     * @param status the value for PUBLIC.NOTIFICATION.STATUS
     *
     * @mbg.generated Fri Jun 16 09:57:35 CST 2023
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.NOTIFICATION.NOTIFIER_NAME
     *
     * @return the value of PUBLIC.NOTIFICATION.NOTIFIER_NAME
     *
     * @mbg.generated Fri Jun 16 09:57:35 CST 2023
     */
    public String getNotifierName() {
        return notifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.NOTIFICATION.NOTIFIER_NAME
     *
     * @param notifierName the value for PUBLIC.NOTIFICATION.NOTIFIER_NAME
     *
     * @mbg.generated Fri Jun 16 09:57:35 CST 2023
     */
    public void setNotifierName(String notifierName) {
        this.notifierName = notifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.NOTIFICATION.OUTER_TITLE
     *
     * @return the value of PUBLIC.NOTIFICATION.OUTER_TITLE
     *
     * @mbg.generated Fri Jun 16 09:57:35 CST 2023
     */
    public String getOuterTitle() {
        return outerTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.NOTIFICATION.OUTER_TITLE
     *
     * @param outerTitle the value for PUBLIC.NOTIFICATION.OUTER_TITLE
     *
     * @mbg.generated Fri Jun 16 09:57:35 CST 2023
     */
    public void setOuterTitle(String outerTitle) {
        this.outerTitle = outerTitle;
    }
}