package com.example.community.model;

public class Post {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.POSTS.ID
     *
     * @mbg.generated Thu Oct 13 15:08:01 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.POSTS.TITLE
     *
     * @mbg.generated Thu Oct 13 15:08:01 CST 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.POSTS.DESCRIPTION
     *
     * @mbg.generated Thu Oct 13 15:08:01 CST 2022
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.POSTS.GMT_CREATE
     *
     * @mbg.generated Thu Oct 13 15:08:01 CST 2022
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.POSTS.GMT_MODIFIED
     *
     * @mbg.generated Thu Oct 13 15:08:01 CST 2022
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.POSTS.CREATOR
     *
     * @mbg.generated Thu Oct 13 15:08:01 CST 2022
     */
    private Integer creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.POSTS.COMMENT_COUNT
     *
     * @mbg.generated Thu Oct 13 15:08:01 CST 2022
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.POSTS.VIEW_COUNT
     *
     * @mbg.generated Thu Oct 13 15:08:01 CST 2022
     */
    private Integer viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.POSTS.LIKE_COUNT
     *
     * @mbg.generated Thu Oct 13 15:08:01 CST 2022
     */
    private Integer likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.POSTS.TAG
     *
     * @mbg.generated Thu Oct 13 15:08:01 CST 2022
     */
    private String tag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.POSTS.ID
     *
     * @return the value of PUBLIC.POSTS.ID
     *
     * @mbg.generated Thu Oct 13 15:08:01 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.POSTS.ID
     *
     * @param id the value for PUBLIC.POSTS.ID
     *
     * @mbg.generated Thu Oct 13 15:08:01 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.POSTS.TITLE
     *
     * @return the value of PUBLIC.POSTS.TITLE
     *
     * @mbg.generated Thu Oct 13 15:08:01 CST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.POSTS.TITLE
     *
     * @param title the value for PUBLIC.POSTS.TITLE
     *
     * @mbg.generated Thu Oct 13 15:08:01 CST 2022
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.POSTS.DESCRIPTION
     *
     * @return the value of PUBLIC.POSTS.DESCRIPTION
     *
     * @mbg.generated Thu Oct 13 15:08:01 CST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.POSTS.DESCRIPTION
     *
     * @param description the value for PUBLIC.POSTS.DESCRIPTION
     *
     * @mbg.generated Thu Oct 13 15:08:01 CST 2022
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.POSTS.GMT_CREATE
     *
     * @return the value of PUBLIC.POSTS.GMT_CREATE
     *
     * @mbg.generated Thu Oct 13 15:08:01 CST 2022
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.POSTS.GMT_CREATE
     *
     * @param gmtCreate the value for PUBLIC.POSTS.GMT_CREATE
     *
     * @mbg.generated Thu Oct 13 15:08:01 CST 2022
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.POSTS.GMT_MODIFIED
     *
     * @return the value of PUBLIC.POSTS.GMT_MODIFIED
     *
     * @mbg.generated Thu Oct 13 15:08:01 CST 2022
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.POSTS.GMT_MODIFIED
     *
     * @param gmtModified the value for PUBLIC.POSTS.GMT_MODIFIED
     *
     * @mbg.generated Thu Oct 13 15:08:01 CST 2022
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.POSTS.CREATOR
     *
     * @return the value of PUBLIC.POSTS.CREATOR
     *
     * @mbg.generated Thu Oct 13 15:08:01 CST 2022
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.POSTS.CREATOR
     *
     * @param creator the value for PUBLIC.POSTS.CREATOR
     *
     * @mbg.generated Thu Oct 13 15:08:01 CST 2022
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.POSTS.COMMENT_COUNT
     *
     * @return the value of PUBLIC.POSTS.COMMENT_COUNT
     *
     * @mbg.generated Thu Oct 13 15:08:01 CST 2022
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.POSTS.COMMENT_COUNT
     *
     * @param commentCount the value for PUBLIC.POSTS.COMMENT_COUNT
     *
     * @mbg.generated Thu Oct 13 15:08:01 CST 2022
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.POSTS.VIEW_COUNT
     *
     * @return the value of PUBLIC.POSTS.VIEW_COUNT
     *
     * @mbg.generated Thu Oct 13 15:08:01 CST 2022
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.POSTS.VIEW_COUNT
     *
     * @param viewCount the value for PUBLIC.POSTS.VIEW_COUNT
     *
     * @mbg.generated Thu Oct 13 15:08:01 CST 2022
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.POSTS.LIKE_COUNT
     *
     * @return the value of PUBLIC.POSTS.LIKE_COUNT
     *
     * @mbg.generated Thu Oct 13 15:08:01 CST 2022
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.POSTS.LIKE_COUNT
     *
     * @param likeCount the value for PUBLIC.POSTS.LIKE_COUNT
     *
     * @mbg.generated Thu Oct 13 15:08:01 CST 2022
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.POSTS.TAG
     *
     * @return the value of PUBLIC.POSTS.TAG
     *
     * @mbg.generated Thu Oct 13 15:08:01 CST 2022
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.POSTS.TAG
     *
     * @param tag the value for PUBLIC.POSTS.TAG
     *
     * @mbg.generated Thu Oct 13 15:08:01 CST 2022
     */
    public void setTag(String tag) {
        this.tag = tag;
    }
}